<a href="https://colab.research.google.com/github/aswin-raj2255/numpy/blob/main/num_pi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #numerical python
#array is collection of homogeonous dataype
a=np.array([1,2,3,4,"a"])
print(a[2:3:1])

['3']


In [ ]:
b=np.array([1,2,3,4,5])
print(b[0:2:1])
print(b[-1:-3:-1])
print(b[3::1])
print(b[0:2:1])
print(b[-4::-1])

[1 2]
[5 4]
[4 5]
[1 2]
[2 1]


In [ ]:
#dimension
c=np.array([1,2,3,4,5])
b=np.array([[3,4,4],[1,2,6]])
c.ndim #dimension =1 is vector
b.ndim
print(b.shape)

(2, 3)


In [ ]:
#create a 2x2 matrix 2,3,4,5
d=np.array([[2,3],[4,5]])
print(d.shape)
print(d.ndim)
print(d.size)

(2, 2)
2
4


In [ ]:
#create a 2x3 matrix find size shape dim
z=np.array([[2,3,4],[4,5,6]])
print(z.shape)
print(z.ndim)
print(z.size)


(2, 3)
2
6


In [ ]:
#4x2
g=np.array([[1,2],[3,4],[5,6],[7,8]])
print(g)
print(g.shape)
print(g.ndim)
print(g.size)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
2
8


In [ ]:
#create a 4x4 matrix
import numpy as np
g=np.array([[1,2,4,5],[3,4,6,7],[5,6,7,4],[7,8,6,2]])
print(g)
print(g.shape)
print(g.ndim)
print(g.size)
print(g[0])
print(g[:,0])
print(g[1,3])
print(g[2,2])
print(g[3,1:])
print(g[1:,1:])

[[1 2 4 5]
 [3 4 6 7]
 [5 6 7 4]
 [7 8 6 2]]
(4, 4)
2
16
[1 2 4 5]
[1 3 5 7]
7
7
[8 6 2]
[[4 6 7]
 [6 7 4]
 [8 6 2]]


In [ ]:
#zero matrix
z=np.zeros([3,3,3],dtype=int)
z

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:
#create two 2x2 np.matrix
z=np.zeros([2,2,2],dtype=int)
z


array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [ ]:
#matrix adittion
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[4,1]])
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)#not matrix mult
print(a@b)#matril mul
print(a.dot(b))
print(a/b)

[[1 2]
 [3 4]]
[[1 2]
 [4 1]]
[[2 4]
 [7 5]]
[[ 0  0]
 [-1  3]]
[[ 1  4]
 [12  4]]
[[ 9  4]
 [19 10]]
[[ 9  4]
 [19 10]]


In [ ]:
#full matrix
z=np.full([3,4,4],6,dtype=int)
z

array([[[6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6]],

       [[6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6]],

       [[6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6]]])

In [ ]:
#3x4 value 9 complex
z=np.full([3,4],9,dtype=complex)
z

array([[9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j]])

In [ ]:
#identity matrix
np.identity(3,dtype=int)
z=np.eye(5)
z

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#create 4x4 matrix
b=np.array([[1,2,3,4],[2,3,1,6],[1,23,4,5],[3,2,3,6]])
a=b.reshape(8,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 2,  3],
       [ 1,  6],
       [ 1, 23],
       [ 4,  5],
       [ 3,  2],
       [ 3,  6]])

In [ ]:
#arange
a=np.arange(1,11,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:

#5x2 matrix usig arange
a=np.arange(1,11,1)
a.reshape(5,2)



array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#3x3 matrix with float val
a=

In [ ]:
a=np.arange(1,11,1).reshape(5,2)
print(a)
print(a.max(axis=1))


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[ 2  4  6  8 10]


In [4]:
import numpy as np
a=np.array([[1,2,3],[5,3,1],[9,7,6]])
print(a)
b=np.sort(a,axis=1)
print(b)
c=np.argsort(a,axis=1)
print(c)

[[1 2 3]
 [5 3 1]
 [9 7 6]]
[[1 2 3]
 [1 3 5]
 [6 7 9]]
[[0 1 2]
 [2 1 0]
 [2 1 0]]


In [7]:
a=np.array([[1,2,3],[5,3,1],[9,7,6]])
print(a)
b=a.flatten()
print(b)

[[1 2 3]
 [5 3 1]
 [9 7 6]]
[1 2 3 5 3 1 9 7 6]
